---
title: "INFO 201 Final Project: "
author: "Nicole Ham, Ruslana Korolov, Hanna Pan"
date: "`6/6/2025`"
output: html_document
---

## Method

```{r}
library(tidyverse)
library(dplyr)
library(stringr)
```

```{r}
habits_df <- read_csv("student_habits_performance.csv")
social_df <- read_csv("smmh.csv")

habits_df_clean <- habits_df %>%
  mutate(
    age = as.numeric(age),
    gender = tolower(trimws(gender))
  ) %>%
  filter(!is.na(age), !is.na(gender))

social_df_clean <- social_df %>%
  mutate(
    age = as.numeric(`1. What is your age?`),
    gender = tolower(trimws(`2. Gender`))
  ) %>%
  filter(!is.na(age), !is.na(gender))

habits_indexed <- habits_df_clean %>%
  group_by(age, gender) %>%
  mutate(row_id = row_number()) %>%
  ungroup()

social_indexed <- social_df_clean %>%
  group_by(age, gender) %>%
  mutate(row_id = row_number()) %>%
  ungroup()

merged_df <- inner_join(
  habits_indexed,
  social_indexed,
  by = c("age", "gender", "row_id")
)

merged_df <- merged_df %>%
  select(-student_id, 
         -netflix_hours,
         -part_time_job,
         -diet_quality,
         -parental_education_level,
         -extracurricular_participation,
         -row_id,
         -Timestamp, 
         -`1. What is your age?`,
         -`2. Gender`,
         -`3. Relationship Status`,
         -`5. What type of organizations are you affiliated with?`,
         -`6. Do you use social media?`,
         -`8. What is the average time you spend on social media every day?`)
```


```{r}
head(merged_df)
names(merged_df)
```

## Results

### RQ1: What is the factor that contributes to the greatest academic performance?

```{r}
# Multiple Linear Regression using ggcorrplot

library(ggcorrplot)

model <- lm(exam_score ~ study_hours_per_day + social_media_hours + attendance_percentage + sleep_hours +
            exercise_frequency + internet_quality + mental_health_rating,
            data = merged_df)

summary(model)
```

```{r}
# Feature Importance via Machine Learning
library(randomForest)

rf_data <- merged_df %>%
  select(exam_score, study_hours_per_day, social_media_hours,
         attendance_percentage, sleep_hours,
         exercise_frequency, internet_quality, mental_health_rating)

rf_data$internet_quality <- as.factor(rf_data$internet_quality)

rf_model <- randomForest(exam_score ~ ., data = rf_data, importance = TRUE)

importance(rf_model)
varImpPlot(rf_model)
```

```{r}
# Correlation Heatmap using RF model
importance_df <- as.data.frame(importance(rf_model)) %>%
  rownames_to_column("variable") %>%
  arrange(desc(`%IncMSE`))

ggplot(importance_df, aes(x = reorder(variable, `%IncMSE`), y = `%IncMSE`)) +
  geom_col(fill = "skyblue") +
  coord_flip() +
  labs(title = "Variable Importance (%IncMSE)",
       x = "Variable", y = "% Increase in MSE if Removed")

```

### RQ2: How does the amount of time an individual spends on social media and the impact it has on their mental health?

``` {r}
# trying to find correlation between social media hours and mental health rating

# plot relationship to see trend
ggplot(merged_df, aes(x = social_media_hours, y = mental_health_rating)) +
  geom_jitter(width = 0.3, height = 0.3, alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  labs(
    title = "Social Media Usage vs Mental Health Rating",
    x = "Hours Spent on Social Media",
    y = "Mental Health Rating (1 = Very Poor, 10 = Excellent)"
  )


# group health rating by hour for visualization
line_df <- merged_df %>%
  group_by(social_media_hours) %>%
  summarize(avg_mh = mean(mental_health_rating, na.rm = TRUE))

# line plot
ggplot(line_df, aes(x = social_media_hours, y = avg_mh)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Average Mental Health Rating by Social Media Hours",
    x = "Hours on Social Media (per day)",
    y = "Average Mental Health Rating"
  )

# correlation between vars
cor.test(merged_df$social_media_hours, merged_df$mental_health_rating, use = "complete.obs")
# corr is around 0.002 --> basically no linear trend?? let's explore more

```

``` {r}
# Trying to see if grouping hours by usage (low, medium, high) will help us find some sort of trend
grouping_hours <- merged_df %>%
  mutate(usage_group = case_when(
    social_media_hours <= 1 ~ "Low (0–1 hrs)",
    social_media_hours <= 3 ~ "Medium (1–3 hrs)",
    social_media_hours >= 3 ~ "High (3+ hrs)"))

grouping_hours %>%
  group_by(usage_group) %>%
  summarize(avg_mental_health = mean(mental_health_rating, na.rm = TRUE),
    count = n())

ggplot(grouping_hours, aes(x = usage_group, y = mental_health_rating, fill = usage_group)) +
  geom_boxplot() +
  labs(title = "Mental Health Ratings by Social Media Usage (by hours) Group",
    x = "Usage Group by Hours",
    y = "Mental Health Rating",
    fill = "Usage (by hours)")

```

``` {r}
# Testing if there's a trend between usage and gender with mental health

test_with_gender <- merged_df %>%
  group_by(gender) %>%
  summarize(avg_mh = mean(mental_health_rating, na.rm = TRUE),
    avg_sm = mean(social_media_hours, na.rm = TRUE),
    n = n())

with_gender_data <- merged_df %>%
  group_by(social_media_hours, gender) %>%
  summarize(avg_mh = mean(mental_health_rating, na.rm = TRUE),
    count = n(),
    .groups = "drop")

ggplot(with_gender_data, aes(x = social_media_hours, y = avg_mh, color = gender)) +
  geom_line(size = 0.5) +
  geom_point() +
  labs(
    title = "Average Mental Health Rating by Social Media Usage and Gender",
    x = "Social Media Usage (by hours)",
    y = "Average Mental Health Rating",
    fill = "Gender")

ggplot(merged_df, aes(x = social_media_hours, y = mental_health_rating, color = gender)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Mental Health vs. Social Media Hours by Gender",
    x = "Daily Social Media Hours",
    y = "Mental Health Rating",
    fill = "Gender")

```

### RQ3: Is there a correlation between a student’s mental health and their exam score? Are there any factors that contribute to mental health?
```{r}
ggplot(merged_df, aes(x = mental_health_rating, y = exam_score)) +
  geom_point(color = "steelblue", size = 1, alpha = 0.65) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  scale_x_continuous(breaks = 1:10, limits = c(1, 10)) +
  labs(
    title = "Relationship Between Mental Health Rating and Exam Score",
    x = "Mental Health Rating",
    y = "Exam Score")
```

```{r}
cor_val <- cor(merged_df$mental_health_rating, merged_df$exam_score, use = "complete.obs", method = "pearson")

# View result
print(cor_val)
```
```{r}
merged_df %>%
  mutate(feel_depressed = factor(`18. How often do you feel depressed or down?`,
                                 levels = 1:5,
                                 labels = c("1\nNot at all", "2", "3", "4", "5\nExtremely"))) %>%
  ggplot(aes(x = feel_depressed, y = exam_score)) +
  geom_violin(fill = "steelblue", alpha = 0.6) +
  geom_jitter(width = 0.2, alpha = 0.4, color = "darkblue") +
  labs(title = "Exam Score vs. Feeling Depressed",
       x = "How often do you feel depressed or down?",
       y = "Exam Score")
```


```{r}
vars <- c("sleep_hours", "exercise_frequency", "social_media_hours", 
          "study_hours_per_day", "attendance_percentage", "exam_score")

long_data <- merged_df %>%
  select(all_of(vars), mental_health_rating) %>%
  pivot_longer(cols = all_of(vars), names_to = "Variable", values_to = "val")

ggplot(long_data, aes(x = val, y = mental_health_rating)) +
  geom_point(alpha = 0.4, color = "steelblue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  facet_wrap(~ Variable, scales = "free_x") +
  labs(title = "Mental Health Rating vs. Various Factors",
       x = "Value of Variable",
       y = "Mental Health Rating")
```

