---
title: "Nicole_Analysis"
author: "Nicole Ham"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(dplyr)
library(stringr)
```

```{r}
habits_df <- read_csv("student_habits_performance.csv")
social_df <- read_csv("smmh.csv")

habits_df_clean <- habits_df %>%
  mutate(
    age = as.numeric(age),
    gender = tolower(trimws(gender))
  ) %>%
  filter(!is.na(age), !is.na(gender))

social_df_clean <- social_df %>%
  mutate(
    age = as.numeric(`1. What is your age?`),
    gender = tolower(trimws(`2. Gender`))
  ) %>%
  filter(!is.na(age), !is.na(gender))

habits_indexed <- habits_df_clean %>%
  group_by(age, gender) %>%
  mutate(row_id = row_number()) %>%
  ungroup()

social_indexed <- social_df_clean %>%
  group_by(age, gender) %>%
  mutate(row_id = row_number()) %>%
  ungroup()

merged_df <- inner_join(
  habits_indexed,
  social_indexed,
  by = c("age", "gender", "row_id")
)

merged_df <- merged_df %>%
  select(-student_id, 
         -netflix_hours,
         -part_time_job,
         -diet_quality,
         -parental_education_level,
         -extracurricular_participation,
         -row_id,
         -Timestamp, 
         -`1. What is your age?`,
         -`2. Gender`,
         -`3. Relationship Status`,
         -`5. What type of organizations are you affiliated with?`,
         -`6. Do you use social media?`,
         -`8. What is the average time you spend on social media every day?`)
```

```{r}
head(merged_df)
names(merged_df)
```

## Research Question: Is there a correlation between a student’s mental health and their exam score? Are there any factors that contribute to mental health?
```{r}
ggplot(merged_df, aes(x = mental_health_rating, y = exam_score)) +
  geom_point(color = "steelblue", size = 1, alpha = 0.65) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  scale_x_continuous(breaks = 1:10, limits = c(1, 10)) +
  labs(
    title = "Relationship Between Mental Health Rating and Exam Score",
    x = "Mental Health Rating",
    y = "Exam Score")
```

```{r}
cor_val <- cor(merged_df$mental_health_rating, merged_df$exam_score, use = "complete.obs", method = "pearson")

# View result
print(cor_val)
```

```{r}
vars <- c("sleep_hours", "exercise_frequency", "social_media_hours", 
          "study_hours_per_day", "attendance_percentage", "exam_score")

long_data <- merged_df %>%
  select(all_of(vars), mental_health_rating) %>%
  pivot_longer(cols = all_of(vars), names_to = "Variable", values_to = "val")

ggplot(long_data, aes(x = val, y = mental_health_rating)) +
  geom_point(alpha = 0.4, color = "steelblue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  facet_wrap(~ Variable, scales = "free_x") +
  labs(title = "Mental Health Rating vs. Various Factors",
       x = "Value of Variable",
       y = "Mental Health Rating")

# Instead of plotting the scatter plots, plot the regression line for each factor instead
```


```{r}
merged_df %>%
  mutate(feel_depressed = factor(`18. How often do you feel depressed or down?`,
                                 levels = 1:5,
                                 labels = c("1\nNot at all", "2", "3", "4", "5\nExtremely"))) %>%
  ggplot(aes(x = feel_depressed, y = exam_score)) +
  geom_violin(fill = "steelblue", alpha = 0.6) +
  geom_jitter(width = 0.2, alpha = 0.4, color = "darkblue") +
  labs(title = "Exam Score vs. Feeling Depressed",
       x = "How often do you feel depressed or down?",
       y = "Exam Score")
```
- seeking help
- getting medication


```{r}
names(merged_df)
```